apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'argocd-apps/chart/hello-world'
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/chart/hello-world/values.yaml
    - repoURL: 'https://github.com/simonliska/helm-ardiff'
      ref: values

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true