apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/simonliska/helm-ardiff'
      path: argocd-apps/chart/hello-world
      targetRevision: HEAD
      helm:
        valueFiles:
          - argocd-apps/chart/hello-world/values.yaml
  destination:
    name: in-cluster
    namespace: default